### ISSUE TITLE
EC2Box on Safari iOS

### ISSUE THREAD

**Issue by charliejones** [skavanagh/EC2Box#63]
I can log into EC2Box on my iPad (iOS 10.3.2) using Safari and Chrome. When I try to bring up a terminal (or multiple terminals), all I get is a collapsed gray bar with the terminal name in it. There is no apparent way to expand these bars to show the actual terminal. Safari for iOS is web socket compliant, so it's not clear what the problem might be.

Is anyone else using EC2Box from an iPad?

**Comment by skavanagh** [comment]
I've not used it on a iPad or any tablet (so I'm not sure).  Those symptoms are exactly what happens when a websocket connection can't be established back to the server.  I'm not sure about mobile Safari, but I've had issues in regular Safari and websockets when using self-signed certs.  There is a note about it here -
 https://github.com/skavanagh/EC2Box#prerequisites
